version: "3"
 
services:
  app:
    container_name: node
    build: ./
    ports:
      - 9050:9050
    volumes:
      - ./:/usr/src/app
    stdin_open: true
    tty: true
    command: ["npm", "run", "serve"]
